name: Backend Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Console file
        run: |
           pwd
           ls -l

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact 
          path: coverage/clover.xml

      //- uses: sonarsource/sonarqube-scan-action@master
      //  env:
        //  SONAR_TOKEN: 'sqp_ac83bfbfd421ef0fd4a119c000f7bbf71210ba30'
          //SONAR_HOST_URL: 'http://54.236.251.70:9000'
      
 
